name: Build tun2socks

on:
  push:
    branches:
      - main  # أو الفرع الذي تود تفعيله للبناء
  pull_request:
    branches:
      - main  # نفس الشيء

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'  # اختر الإصدار الذي تحتاجه من Go

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        go install golang.org/x/mobile/cmd/gomobile@latest  # استخدم go install هنا بدلاً من go get
        gomobile init  # قم بإعداد gomobile للـ Android

    - name: Build tun2socks
      run: |
        cd go-tun2socks
        make  # أو أي أمر بناء آخر تحتاجه
